# Site settings
title: sublime-jekyll
email: me@rymo.io
description: A Sublime Text package for Jekyll static sites.
baseurl: "/sublime-jekyll"
url: "https://rymo.io/"
twitter_username: rymoio
github_username:  23maverick23

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
